---
mirror:
  - type: wget
    src: https://mirror.umd.edu/centos/7/os/x86_64/
    dest: /home/mike/drop/cattleDrive/wget/
  - type: rsync
    src: rsync://mirrors.rit.edu/centos/7/os/x86_64/
    dest: /home/mike/drop/cattleDrive/rsync/
  - type: oci
    src: hello-world:latest
    dest: /home/mike/drop/cattleDrive/docker/
    compress: false # if omitted, defaults to true
  - type: oci
    src: quay.io/prometheus/node-exporter
    dest: /home/mike/drop/cattleDrive/docker/
    compress: true # if omitted, defaults to true
  - type: helm
    repo: https://helm.traefik.io/traefik 
    chart: traefik
    dest: /home/mike/drop/cattleDrive/helm/traefik/
    cleanup: false #if omitted, defaults to true
    pullImages: true #if omitted, defaults to false
  - type: reposync
    src: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/
    dest: /home/mike/drop/cattleDrive/kubernetes/el7/x86_64/
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg ## if omitted, will not perform gpgkey check and not include it in the repo definition
  - type: galaxy
    src: "kubernetes.core"
    dest: "/home/mike/drop/cattleDrive/galaxy/"